"""empty message

Revision ID: 6a92dc3644fc
Revises: 1ed3ffbf6bb9
Create Date: 2023-03-25 13:53:08.546510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a92dc3644fc'
down_revision = '1ed3ffbf6bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('name', sa.Text(), nullable=True))
    op.drop_column('project', 'project_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_name', sa.TEXT(), nullable=True))
    op.drop_column('project', 'name')
    # ### end Alembic commands ###
