"""empty message

Revision ID: 1ace9f34f95f
Revises: 
Create Date: 2023-03-26 21:00:15.319365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ace9f34f95f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('login', sa.String(length=20), nullable=False),
    sa.Column('hashed', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('login')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
